
tasks:
  - name: Install AWS CLI and Configure
    init: |
     env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/aws_cli_install
  - name: Install Terraform
    before: |
      source ./bin/terraform_cli_install

vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform