#!/usr/bin/env bash

# Package the lambda code
zip -r function.zip lambda_function.py

# Create the Lambda function
aws lambda create-function \
  --function-name CulturalHarmonyFunction \
  --runtime python3.9 \
  --handler lambda_function.lambda_handler \
  --role arn:aws:iam::XXXXXXXXX:role/achaminLambdaRole \
  --zip-file fileb://function.zip \
  --timeout 30 \
  --memory-size 512